name: Publish

on:
  push:
    branches:
      - alpha

  pull_request:
    branches:
      - beta
      - main

  workflow_dispatch:
    branches:
      - alpha
      - beta
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Show ref
        run: |
          echo "${{ env.GITHUB_BASE_REF_SLUG || env.GITHUB_REF_SLUG }}"

      - name: Curl kit.zip
        run: |
          curl -L https://github.com/johnlindquist/kit/archive/refs/heads/${{ env.GITHUB_BASE_REF_SLUG || env.GITHUB_REF_SLUG }}.zip -o ./../kit.zip

      - name: Curl kenv.zip
        run: |
          curl -L https://github.com/johnlindquist/kenv/archive/refs/heads/${{ env.GITHUB_BASE_REF_SLUG || env.GITHUB_REF_SLUG }}.zip -o ./../kenv.zip

      - name: ls parent paths
        run: |
          pwd
          ls ./

      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          yarn install --network-timeout 1000000

      - name: electron-build install
        run: |
          yarn install-electron-deps

      - name: pwd
        run: |
          pwd

      - name: ls cwd
        run: |
          ls ./
          ls ./../

      - name: Find .zips
        run: |
          find ./../../ -name "kit.zip"

      - name: Bundle kit and kenv in assets
        run: |
          mv /Users/runner/work/kitapp/kit.zip ./assets/kit.zip && mv /Users/runner/work/kitapp/kenv.zip ./assets/kenv.zip

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.5.3
        with:
          semantic_version: 16
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]

      - name: yarn build
        run: |
          yarn build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn electron-builder --publish always --mac
