name: Publish

on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout kit repo
        uses: actions/checkout@v2
        with:
          repository: 'johnlindquist/kit'
          path: '.kit'

      - name: Bundle Latest Node
        run: |
          bash .kit/install-node.sh --prefix .kit/node --platform darwin

      - name: Create kit.zip
        run: |
          zip kit-mac.zip .kit -r -x "*.git*" "src/**/*"
          mv kit-mac.zip ./../kit-mac.zip

      - name: Checkout kenv repo
        uses: actions/checkout@v2
        with:
          repository: 'johnlindquist/kenv'
          path: .kenv

      - name: Create kenv.zip
        run: |
          zip kenv.zip .kenv -r -x "*.git*" "src/**/*"
          mv kenv.zip ./../kenv.zip

      - name: ls parent paths
        run: |
          pwd
          ls ./

      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          yarn install --network-timeout 1000000

      - name: electron-build install
        run: |
          yarn install-electron-deps

      - name: pwd
        run: |
          pwd

      - name: ls cwd
        run: |
          ls ./
          ls ./../

      - name: Find .zips
        run: |
          find ./../../ -name "kit-mac.zip"

      - name: Bundle kit and kenv in assets
        run: |
          mv /Users/runner/work/kitapp/kit-mac.zip ./assets/kit-mac.zip && mv /Users/runner/work/kitapp/kenv.zip ./assets/kenv.zip

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.5.3

      - name: yarn build
        run: |
          yarn build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn electron-builder --publish always --mac
