name: Publish

on:
  push:
    branches:
      - alpha
      - beta
      - main
      - windows

  workflow_dispatch:
    branches:
      - alpha
      - beta
      - main
      - windows

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic # Need an `id` for output variables
        with:
          dry_run: true
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              {
                name: 'windows',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify that Semantic Release updated src/package.json
        run: |
          cat src/package.json

      - name: Echo the version number
        uses: johnlindquist/kit-action@main
        with:
          script: echo $RELEASE_VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Assets
        uses: johnlindquist/kit-action@main
        with:
          script: create-assets ${{ steps.semantic.outputs.new_release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: yarn && yarn add @johnlindquist/kit
        run: |
          yarn
          yarn add "@johnlindquist/kit"

      - name: Publish windows
        if: matrix.os == 'windows-latest'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build
          cd ./src
          yarn remove node-mac-permissions
          cat ./package.json
          cd ..
          echo "--- Done removing mac deps ---\n\n"
          yarn electron-builder --publish always --win

      - name: Publish linux
        if: matrix.os == 'ubuntu-latest'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build
          cd ./src
          yarn remove node-mac-permissions
          cat ./package.json
          cd ..
          echo "--- Done removing mac deps ---\n\n"
          yarn electron-builder --publish always --linux

      - name: Publish mac
        if: matrix.os == 'macos-latest'
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn build
          yarn electron-builder --publish always --mac
