name: Publish

on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          yarn install --network-timeout 1000000

      - name: electron-build install
        run: |
          yarn install-electron-deps

      - name: yarn build
        run: |
          yarn build

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.5.3

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn electron-builder --publish always --mac

      - name: Clone kit
        run: |
          git clone https://github.com/johnlindquist/kit.git ~/.kit

      - name: Install Kit
        run: |
          cd ~/.kit
          bash ./install-node.sh --prefix ./node
          ./node/bin/npm install --prefix ./
          ./node/bin/npm install @octokit/rest --prefix ./

      - name: Tag Kit
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          cd ~/.kit
          ./script ./ci/create-tag.js ${{ steps.semantic.outputs.new_release_version }}
