name: Publish

on:
  push:
    branches:
      - alpha
      - beta
      - main

  workflow_dispatch:
    branches:
      - alpha
      - beta
      - main

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Show ref
        run: |
          echo "${{ env.GITHUB_BASE_REF_SLUG || env.GITHUB_REF_SLUG }}"
          echo "release_channel=${{ env.GITHUB_BASE_REF_SLUG || env.GITHUB_REF_SLUG }}" >> $GITHUB_ENV

      - name: ls parent paths
        run: |
          pwd
          ls ./

      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - uses: c-hive/gha-yarn-cache@v1

      - name: yarn
        run: |
          yarn

      - name: yarn install-electron-deps
        run: |
          yarn install-electron-deps

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.5.3
        with:
          semantic_version: 16
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]

      - name: yarn build
        run: |
          yarn build

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn electron-builder --publish always --mac
