name: Publish

on:
  push:
    branches:
      - master
      - beta

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install dependencies
        run: |
          yarn install --network-timeout 1000000

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.3

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn postinstall && yarn build && yarn electron-builder --publish always --mac

      - name: Clone simplescripts
        run: |
          git clone https://github.com/johnlindquist/simplescripts.git ~/.simplesdk

      - name: Install Simple Scripts
        run: |
          cd ~/.simplesdk
          bash ./setup/install-node.sh --prefix ./node
          ./node/bin/npm install --prefix ./
          ./node/bin/npm install @octokit/rest --prefix ./

      - name: Tag Simple Scripts
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          cd ~/.simplesdk
          bash ./simple.sh ./setup/create-tag.js ${{ steps.semantic.outputs.new_release_version }}
