name: Publish

on:
  push:
    branches:
      - main

  workflow_dispatch:
    branches:
      - main

jobs:
  publish-mac:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Install Node, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.2

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.7.0
        with:
          semantic_version: 16
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',

            ]

      - uses: c-hive/gha-yarn-cache@v1

      - name: yarn
        run: |
          yarn add "@johnlindquist/kit"
          yarn

      - name: Publish Mac
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEBUG=electron-rebuild yarn install-electron-deps
          yarn build
          yarn electron-builder --publish always -m
